version: 2
updates:
- package-ecosystem: docker
  directory: "/epgstation"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/kea-dhcp4"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/kea-dhcp6"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/radio-recorder"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python
    versions:
    - 3.9.1.pre.alpine
    - 3.9.2.pre.alpine
    - 3.9.3.pre.alpine
  - dependency-name: golang
    versions:
    - 1.16.0.pre.alpine
    - 1.16.1.pre.alpine
    - 1.16.2.pre.alpine
- package-ecosystem: docker
  directory: "/ip-notify"
  schedule:
    interval: daily
  open-pull-requests-limit: 10